version: '3.8'
services:
  postgres96:
    container_name: pgsql96
    image: postgres:9.6
    deploy:
      resources:
        limits:
          memory: 3048M
        reservations:
          memory: 3048M
    restart: always
    environment:
      POSTGRES_USER: jiradbuser
      POSTGRES_PASSWORD: mestre
    ports:
      - 5432:5432
    volumes:
      - $PWD/datadir:/var/lib/postgresql/data 
    networks:
      - docker-jira-common-network
networks: 
  docker-jira-common-network:
    external: true
