# Use postgres/example user/password credentials
version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mestre
      POSTGRES_USER: jiradbuser
      POSTGRES_PASSWORD: mestre
    ports:
      - 5432:5432
    volumes:
      - $PWD/datadir:/var/lib/postgresql/data 
    networks:
      - docker-jira-common-network
networks: 
  docker-jira-common-network:
    external: true
